### PR TITLE
Adding foreign key constraint and E/R model diagram

### PR DESCRIPTION
**Pull request by mat013**

### CODE REVIEW

**Comment by sridoodla** [comment]
Doesn't seem to work. Gives me an error.

```
ERROR:  relation "order_details" does not exist
LINE 1: INSERT INTO order_details VALUES (10335, 32, 25.6000004, 6, ...
                    ^
ERROR:  relation "order_details" does not exist
LINE 1: INSERT INTO order_details VALUES (10335, 51, 42.4000015, 48,...
                    ^
ERROR:  relation "order_details" does not exist
LINE 1: INSERT INTO order_details VALUES (10336, 4, 17.6000004, 18, ...
                    ^
ERROR:  relation "order_details" does not exist
LINE 1: INSERT INTO order_details VALUES (10337, 23, 7.19999981, 40,...

```

some of the errors I get.

The code I used is 

```
psql -U postgres my_db < dump.sql
```

**Comment by pthom** [comment]
Thanks for the PR and the diagram.
There is an issue with your modifications though (using psql 9.5.5)

It gives the following error :
````
ERROR:  permission denied to create "pg_catalog.categories"
````

I guess it can be corrected by re-dumping your database.

Alternatively, I saw that it can be corrected by removing the following line at the beginning of the file
````
SET search_path = northwind, pg_catalog;
````
and removing the lines below near the end

````
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA northwind TO postgres;
GRANT ALL ON SCHEMA northwind TO PUBLIC;
````

Can you modify your PR in order to correct this ?

**Comment by mat013** [comment]
Hi 

I will do it as soon as I have time... I am little bit tight on time at the moment :)

**Comment by mat013** [comment]
@sridoodla Are you sure my PR is causing that. what I have done is basically added removing the tables if they exist, and in the end adding fk constraints, and I have also removed foo and ship_tmp as they are not part of the official drawing. 

Your fault is kind of suggesting that the table has not been created . I can look at it but I am tight on time at the moment, so it may take a while

**Comment by mat013** [comment]
@sridoodla 

It seemed like when running the script following error occurred, which most likely caused the tables to not be created and then you got the insertion errors

ERROR:  permission denied to create "pg_catalog.categories"
DETAIL:  System catalog modifications are currently disallowed.
ERROR:  permission denied to create "pg_catalog.customercustomerdemo"
DETAIL:  System catalog modifications are currently disallowed.

I did as @pthom suggested and it seems to work.

I am not an expert and are unsure what the reason is behind it is. So maybe @pthom can chip in. I just needed a toy database with sufficient complexity to work with :)

@pthom I found 10 minutes to fix the issue and I did as you requested and it seemed to work. otherwise let me know

**Comment by pthom** [comment]
Ok I merged the PR

**Comment by dwanneruchi** [comment]
Hoping to use this for a course I am teaching - do you have information on licensing? I don't want to break any rules on this, but appreciate how you've put it together for postgreSQL (which we are using).

**Comment by mat013** [comment]
I Google it i think the image was from codeplex

**Pull request merged**
